const { Pricelist } = require("../models");

const pricelistData = [
  {
    articleNo: "1234567890",
    productService: "This is a test product with fifty characters this!",
    inPrice: 900500,
    price: 1500800,
    unit: "kilometers/hour",
    inStock: 2500600,
    description: "This is the description with fifty characters this",
  },
  {
    articleNo: "PROD001",
    productService: "Premium Laptop Computer",
    inPrice: 80000,
    price: 120000,
    unit: "piece",
    inStock: 15,
    description: "High-performance laptop with latest specifications and extended warranty",
  },
  {
    articleNo: "PROD002",
    productService: "Wireless Mouse",
    inPrice: 1500,
    price: 2500,
    unit: "piece",
    inStock: 50,
    description: "Ergonomic wireless mouse with precision tracking",
  },
  {
    articleNo: "PROD003",
    productService: "Mechanical Keyboard",
    inPrice: 3500,
    price: 5500,
    unit: "piece",
    inStock: 25,
    description: "RGB mechanical keyboard with customizable switches",
  },
  {
    articleNo: "PROD004",
    productService: "4K Monitor",
    inPrice: 25000,
    price: 35000,
    unit: "piece",
    inStock: 10,
    description: "27-inch 4K monitor with HDR support and adjustable stand",
  },
  {
    articleNo: "PROD005",
    productService: "Webcam HD",
    inPrice: 800,
    price: 1200,
    unit: "piece",
    inStock: 30,
    description: "1080p webcam with built-in microphone and privacy cover",
  },
  {
    articleNo: "PROD006",
    productService: "USB-C Hub",
    inPrice: 1200,
    price: 1800,
    unit: "piece",
    inStock: 40,
    description: "7-in-1 USB-C hub with HDMI, USB ports, and SD card reader",
  },
  {
    articleNo: "PROD007",
    productService: "Gaming Headset",
    inPrice: 2000,
    price: 3200,
    unit: "piece",
    inStock: 20,
    description: "Surround sound gaming headset with noise-canceling microphone",
  },
  {
    articleNo: "PROD008",
    productService: "External SSD",
    inPrice: 8000,
    price: 12000,
    unit: "piece",
    inStock: 35,
    description: "1TB external SSD with USB 3.1 Gen 2 interface",
  },
  {
    articleNo: "PROD009",
    productService: "Wireless Charger",
    inPrice: 1500,
    price: 2200,
    unit: "piece",
    inStock: 45,
    description: "Fast wireless charging pad compatible with all Qi devices",
  },
  {
    articleNo: "PROD010",
    productService: "Bluetooth Speaker",
    inPrice: 2500,
    price: 3800,
    unit: "piece",
    inStock: 18,
    description: "Portable Bluetooth speaker with 20-hour battery life",
  },
  {
    articleNo: "PROD011",
    productService: "Tablet Stand",
    inPrice: 600,
    price: 900,
    unit: "piece",
    inStock: 60,
    description: "Adjustable aluminum tablet stand with anti-slip base",
  },
  {
    articleNo: "PROD012",
    productService: "Cable Organizer",
    inPrice: 300,
    price: 500,
    unit: "piece",
    inStock: 100,
    description: "Set of 10 cable organizers for desk management",
  },
  {
    articleNo: "PROD013",
    productService: "Desk Lamp",
    inPrice: 1800,
    price: 2800,
    unit: "piece",
    inStock: 22,
    description: "LED desk lamp with adjustable brightness and color temperature",
  },
  {
    articleNo: "PROD014",
    productService: "Laptop Cooling Pad",
    inPrice: 1200,
    price: 1800,
    unit: "piece",
    inStock: 28,
    description: "Cooling pad with dual fans and adjustable height",
  },
  {
    articleNo: "PROD015",
    productService: "USB Microphone",
    inPrice: 3500,
    price: 5200,
    unit: "piece",
    inStock: 12,
    description: "Professional USB microphone for streaming and recording",
  },
  {
    articleNo: "PROD016",
    productService: "Monitor Arm",
    inPrice: 4000,
    price: 6000,
    unit: "piece",
    inStock: 8,
    description: "Dual monitor arm with gas spring and cable management",
  },
  {
    articleNo: "PROD017",
    productService: "Gaming Mouse Pad",
    inPrice: 800,
    price: 1200,
    unit: "piece",
    inStock: 55,
    description: "Large gaming mouse pad with RGB lighting and non-slip base",
  },
  {
    articleNo: "PROD018",
    productService: "Power Strip",
    inPrice: 1000,
    price: 1500,
    unit: "piece",
    inStock: 70,
    description: "Surge protector power strip with 8 outlets and USB ports",
  },
  {
    articleNo: "PROD019",
    productService: "Laptop Sleeve",
    inPrice: 500,
    price: 800,
    unit: "piece",
    inStock: 80,
    description: "Neoprene laptop sleeve with extra padding and zipper closure",
  },
  {
    articleNo: "PROD020",
    productService: "Screen Cleaner Kit",
    inPrice: 400,
    price: 600,
    unit: "piece",
    inStock: 90,
    description: "Complete screen cleaning kit with microfiber cloth and solution",
  },
  {
    articleNo: "PROD021",
    productService: "Wireless Earbuds",
    inPrice: 4500,
    price: 6800,
    unit: "piece",
    inStock: 16,
    description: "True wireless earbuds with active noise cancellation",
  },
  {
    articleNo: "PROD022",
    productService: "Document Scanner",
    inPrice: 12000,
    price: 18000,
    unit: "piece",
    inStock: 5,
    description: "High-speed document scanner with automatic feed",
  },
  {
    articleNo: "PROD023",
    productService: "Network Switch",
    inPrice: 8000,
    price: 12000,
    unit: "piece",
    inStock: 7,
    description: "8-port gigabit network switch for office networking",
  },
  {
    articleNo: "PROD024",
    productService: "UPS Battery Backup",
    inPrice: 15000,
    price: 22000,
    unit: "piece",
    inStock: 3,
    description: "Uninterruptible power supply with 1500VA capacity",
  },
];

async function seedPricelist() {
  try {
    for (const item of pricelistData) {
      await Pricelist.findOrCreate({
        where: { articleNo: item.articleNo },
        defaults: item,
      });
    }
    console.log("Pricelist data seeded successfully");
  } catch (error) {
    console.error("Error seeding pricelist data:", error);
  }
}

module.exports = seedPricelist;


